<script>
  import PanelHeader from "../PanelHeader.svelte";

  let { panel, crud } = $props();

  const entities = $derived(crud?.entities ?? []);

  function fieldPreview(v) {
    if (v === null || v === undefined) return "—";
    if (typeof v === "boolean") return v ? "yes" : "no";
    return String(v);
  }
</script>

<div class="h-full flex flex-col">
  <PanelHeader
    {panel}
    subtitle="Real CRUD pages generated by mix caravela.gen.live — LiveView + Svelte 5 forms backed by the Ecto context. The routes under /library are the unedited output of the generator, mounted in this same Phoenix endpoint. Open any one in a new tab to see validation, async save, and the visibility-gated Book form live."
  />

  <div class="flex-1 min-h-0 overflow-auto p-6">
    <div class="grid grid-cols-3 gap-5 max-w-6xl">
      {#each entities as entity (entity.id)}
        <article
          class="rounded-xl border border-ink-700/80 bg-ink-900/60 overflow-hidden flex flex-col"
        >
          <header
            class="px-5 py-4 border-b border-ink-700/60 flex items-start justify-between"
          >
            <div>
              <div class="flex items-center gap-2">
                <span class="h-2 w-2 rounded-full bg-{entity.accent}"></span>
                <h2 class="text-[15px] font-semibold text-ink-50">
                  {entity.label}
                </h2>
                <span
                  class="text-[11px] text-{entity.accent} bg-{entity.accent}/10 border border-{entity.accent}/30 rounded-full px-2 py-px"
                >
                  {entity.count} row{entity.count === 1 ? "" : "s"}
                </span>
              </div>
              <code class="text-[11px] text-ink-500 mt-1 block">
                {entity.module}
              </code>
            </div>
          </header>

          <div class="px-5 py-3 text-[12px] text-ink-400 leading-relaxed border-b border-ink-800/50">
            {entity.description}
          </div>

          <ul class="divide-y divide-ink-800/60 flex-1 min-h-0 overflow-auto">
            {#each entity.sample as row}
              <li class="px-5 py-2.5 text-[12px] flex items-start justify-between gap-3">
                <div class="min-w-0 flex-1 space-y-0.5">
                  {#each Object.entries(row.fields) as [key, value], i (i)}
                    <div class="flex items-baseline gap-2 min-w-0">
                      <span class="text-ink-500 w-16 shrink-0 text-[11px] uppercase tracking-wider">
                        {key}
                      </span>
                      <span class="text-ink-200 truncate">{fieldPreview(value)}</span>
                    </div>
                  {/each}
                </div>
                <a
                  href={row.edit_path}
                  target="_blank"
                  rel="noopener"
                  class="text-[11px] text-ink-500 hover:text-{entity.accent} shrink-0"
                >
                  edit →
                </a>
              </li>
            {:else}
              <li class="px-5 py-5 text-[12px] text-ink-500 italic">
                No rows. Run <code class="text-ink-300">mix caravela_demo.seed</code>.
              </li>
            {/each}
          </ul>

          <footer
            class="px-5 py-3 border-t border-ink-700/60 flex items-center gap-3 text-[12px]"
          >
            <a
              href="/library/{entity.id}"
              target="_blank"
              rel="noopener"
              class="text-{entity.accent} hover:underline"
            >
              open index →
            </a>
            <span class="text-ink-600">·</span>
            <a
              href="/library/{entity.id}/new"
              target="_blank"
              rel="noopener"
              class="text-ink-400 hover:text-ink-100"
            >
              new {entity.id.replace(/s$/, "")}
            </a>
            <span class="flex-1"></span>
            <code class="text-[10px] text-ink-600">/library/{entity.id}</code>
          </footer>
        </article>
      {/each}
    </div>

    <div
      class="mt-6 max-w-6xl rounded-xl border border-ink-700/60 bg-ink-900/40 p-5 text-[12px] text-ink-400 leading-relaxed"
    >
      <div class="text-[11px] text-ink-500 uppercase tracking-widest mb-2">
        What's actually generated
      </div>
      <p class="mb-2">
        Running <code class="text-ink-200">mix caravela.gen.live --with-domain CaravelaDemo.Domains.Library</code>
        emits 22 files across
        <code class="text-ink-200">lib/caravela_demo_web/live/library/</code> and
        <code class="text-ink-200">assets/svelte/library/</code>: one LiveView module per
        page (index, show, form), one form-domain module with declarative
        state + updaters, nine Svelte components with $props() runes and onchange/oninput
        attributes, and a TypeScript type file. You can browse them all
        in the Generators panel.
      </p>
      <p>
        Every edit round-trips through the generated
        <code class="text-ink-200">CaravelaDemo.Library</code> context, which in turn
        runs Caravela's permission checks, changeset hooks, and
        multi-tenant scoping (stubbed out because this domain opts into
        none — see the Tenancy &amp; Versions panel for the multi-tenant
        variant).
      </p>
    </div>
  </div>
</div>
