defmodule CaravelaDemo.Library do
  @moduledoc """
  Generated by Caravela from CaravelaDemo.Domains.Library.

  CRUD context with hooks and standalone authorization.

  Regenerate with `mix caravela.gen.context CaravelaDemo.Domains.Library`.
  Custom code placed below the `# --- CUSTOM ---` marker is preserved.
  """

  import Ecto.Query, only: [preload: 2]

  alias CaravelaDemo.Repo
  alias CaravelaDemo.Library.Author
  alias CaravelaDemo.Library.Book
  alias CaravelaDemo.Library.Publisher

  @doc "List `authors` the caller is allowed to read."
  def list_authors(context \\ %{}) do
    Author
    |> scope_tenant(context)
    |> apply_read_permission(:authors, context)
    |> Repo.all()
  end

  @doc "Fetch a single `author` by id. Returns `nil` if not found or not visible."
  def get_author(id, context \\ %{}) do
    Author
    |> scope_tenant(context)
    |> apply_read_permission(:authors, context)
    |> Repo.get(id)
  end

  @doc "Fetch a single `author` by id. Raises if not found or not visible."
  def get_author!(id, context \\ %{}) do
    Author
    |> scope_tenant(context)
    |> apply_read_permission(:authors, context)
    |> Repo.get!(id)
  end

  @doc "Build an unsaved `author` changeset, for use in forms."
  def change_author(%Author{} = author, attrs \\ %{}) do
    Author.changeset(author, attrs)
  end

  @doc "Create a `author`: authorize, apply on_create hook, insert."
  def create_author(attrs, context \\ %{}) do
    with :ok <- authorize_create(:authors, context) do
      %Author{}
      |> Author.changeset(attrs)
      |> inject_tenant_id(context)
      |> apply_changeset_hook(:on_create, :authors, context)
      |> Repo.insert()
    end
  end

  @doc "Update a `author`: authorize, apply on_update hook, update."
  def update_author(%Author{} = author, attrs, context \\ %{}) do
    with :ok <- authorize_update(:authors, author, context) do
      author
      |> Author.changeset(attrs)
      |> apply_changeset_hook(:on_update, :authors, context)
      |> Repo.update()
    end
  end

  @doc """
  Delete a `author`: authorize, run on_delete hook, delete.

  Accepts either the loaded struct (skipping the read round-trip) or
  the primary-key id (one `get` + one `delete`). Returns
  `{:error, :not_found}` when called by id and the row is invisible
  or missing.
  """
  def delete_author(struct_or_id, context \\ %{})

  def delete_author(%Author{} = author, context) do
    with :ok <- authorize_delete(:authors, author, context),
         :ok <- run_delete_hook(:authors, author, context) do
      Repo.delete(author)
    end
  end

  def delete_author(id, context) when is_binary(id) or is_integer(id) do
    case get_author(id, context) do
      nil -> {:error, :not_found}
      entity -> delete_author(entity, context)
    end
  end

  @doc "List `books` the caller is allowed to read."
  def list_books(context \\ %{}) do
    Book
    |> scope_tenant(context)
    |> apply_read_permission(:books, context)
    |> preload([:author, :publisher])
    |> Repo.all()
  end

  @doc "Fetch a single `book` by id. Returns `nil` if not found or not visible."
  def get_book(id, context \\ %{}) do
    Book
    |> scope_tenant(context)
    |> apply_read_permission(:books, context)
    |> preload([:author, :publisher])
    |> Repo.get(id)
  end

  @doc "Fetch a single `book` by id. Raises if not found or not visible."
  def get_book!(id, context \\ %{}) do
    Book
    |> scope_tenant(context)
    |> apply_read_permission(:books, context)
    |> preload([:author, :publisher])
    |> Repo.get!(id)
  end

  @doc "Build an unsaved `book` changeset, for use in forms."
  def change_book(%Book{} = book, attrs \\ %{}) do
    Book.changeset(book, attrs)
  end

  @doc "Create a `book`: authorize, apply on_create hook, insert."
  def create_book(attrs, context \\ %{}) do
    with :ok <- authorize_create(:books, context) do
      %Book{}
      |> Book.changeset(attrs)
      |> inject_tenant_id(context)
      |> apply_changeset_hook(:on_create, :books, context)
      |> Repo.insert()
    end
  end

  @doc "Update a `book`: authorize, apply on_update hook, update."
  def update_book(%Book{} = book, attrs, context \\ %{}) do
    with :ok <- authorize_update(:books, book, context) do
      book
      |> Book.changeset(attrs)
      |> apply_changeset_hook(:on_update, :books, context)
      |> Repo.update()
    end
  end

  @doc """
  Delete a `book`: authorize, run on_delete hook, delete.

  Accepts either the loaded struct (skipping the read round-trip) or
  the primary-key id (one `get` + one `delete`). Returns
  `{:error, :not_found}` when called by id and the row is invisible
  or missing.
  """
  def delete_book(struct_or_id, context \\ %{})

  def delete_book(%Book{} = book, context) do
    with :ok <- authorize_delete(:books, book, context),
         :ok <- run_delete_hook(:books, book, context) do
      Repo.delete(book)
    end
  end

  def delete_book(id, context) when is_binary(id) or is_integer(id) do
    case get_book(id, context) do
      nil -> {:error, :not_found}
      entity -> delete_book(entity, context)
    end
  end

  @doc "List `publishers` the caller is allowed to read."
  def list_publishers(context \\ %{}) do
    Publisher
    |> scope_tenant(context)
    |> apply_read_permission(:publishers, context)
    |> Repo.all()
  end

  @doc "Fetch a single `publisher` by id. Returns `nil` if not found or not visible."
  def get_publisher(id, context \\ %{}) do
    Publisher
    |> scope_tenant(context)
    |> apply_read_permission(:publishers, context)
    |> Repo.get(id)
  end

  @doc "Fetch a single `publisher` by id. Raises if not found or not visible."
  def get_publisher!(id, context \\ %{}) do
    Publisher
    |> scope_tenant(context)
    |> apply_read_permission(:publishers, context)
    |> Repo.get!(id)
  end

  @doc "Build an unsaved `publisher` changeset, for use in forms."
  def change_publisher(%Publisher{} = publisher, attrs \\ %{}) do
    Publisher.changeset(publisher, attrs)
  end

  @doc "Create a `publisher`: authorize, apply on_create hook, insert."
  def create_publisher(attrs, context \\ %{}) do
    with :ok <- authorize_create(:publishers, context) do
      %Publisher{}
      |> Publisher.changeset(attrs)
      |> inject_tenant_id(context)
      |> apply_changeset_hook(:on_create, :publishers, context)
      |> Repo.insert()
    end
  end

  @doc "Update a `publisher`: authorize, apply on_update hook, update."
  def update_publisher(%Publisher{} = publisher, attrs, context \\ %{}) do
    with :ok <- authorize_update(:publishers, publisher, context) do
      publisher
      |> Publisher.changeset(attrs)
      |> apply_changeset_hook(:on_update, :publishers, context)
      |> Repo.update()
    end
  end

  @doc """
  Delete a `publisher`: authorize, run on_delete hook, delete.

  Accepts either the loaded struct (skipping the read round-trip) or
  the primary-key id (one `get` + one `delete`). Returns
  `{:error, :not_found}` when called by id and the row is invisible
  or missing.
  """
  def delete_publisher(struct_or_id, context \\ %{})

  def delete_publisher(%Publisher{} = publisher, context) do
    with :ok <- authorize_delete(:publishers, publisher, context),
         :ok <- run_delete_hook(:publishers, publisher, context) do
      Repo.delete(publisher)
    end
  end

  def delete_publisher(id, context) when is_binary(id) or is_integer(id) do
    case get_publisher(id, context) do
      nil -> {:error, :not_found}
      entity -> delete_publisher(entity, context)
    end
  end

  # --- Internal: permission + hook dispatch ---------------------------------

  defp apply_read_permission(query, entity, context) do
    CaravelaDemo.Domains.Library.__caravela_permission__(:can_read, entity, query, context)
  end

  defp authorize_create(_entity, _context), do: :ok

  defp authorize_update(_entity, _struct, _context), do: :ok

  defp authorize_delete(_entity, _struct, _context), do: :ok

  defp apply_changeset_hook(changeset, action, entity, context) do
    CaravelaDemo.Domains.Library.__caravela_hook__(action, entity, changeset, context)
  end

  defp run_delete_hook(_entity, _struct, _context), do: :ok

  # --- Internal: multi-tenant scoping --------------------------------------

  defp scope_tenant(query, _context), do: query

  defp inject_tenant_id(changeset, _context), do: changeset

  # --- CUSTOM ---
  # Custom code below this line is preserved on regeneration.
end
