defmodule CaravelaDemoWeb.Router do
  use CaravelaDemoWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {CaravelaDemoWeb.Layouts, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json", "text"]
  end

  scope "/", CaravelaDemoWeb do
    pipe_through :api

    get "/health/live", HealthController, :live
    get "/health/ready", HealthController, :ready
  end

  scope "/", CaravelaDemoWeb do
    pipe_through :browser

    live "/", CommandCenterLive, :index
  end

  # Generated by mix caravela.gen.live CaravelaDemo.Domains.Library --with-domain
  scope "/library", CaravelaDemoWeb.Library do
    pipe_through :browser

    live "/authors", AuthorLive.Index, :index
    live "/authors/new", AuthorLive.Form, :new
    live "/authors/:id", AuthorLive.Show, :show
    live "/authors/:id/edit", AuthorLive.Form, :edit

    live "/books", BookLive.Index, :index
    live "/books/new", BookLive.Form, :new
    live "/books/:id", BookLive.Show, :show
    live "/books/:id/edit", BookLive.Form, :edit

    live "/publishers", PublisherLive.Index, :index
    live "/publishers/new", PublisherLive.Form, :new
    live "/publishers/:id", PublisherLive.Show, :show
    live "/publishers/:id/edit", PublisherLive.Form, :edit
  end
end
