// GENERATED by Caravela from CaravelaDemo.Domains.Library — edit below the CUSTOM marker.
//
// TypeScript interfaces for every entity in the domain. Import into
// Svelte components as `import type { <Entity> } from '<relative>/<context>';`.
//
// Regenerate with `mix caravela.gen.live CaravelaDemo.Domains.Library`.

/**
 * LiveSvelte hook handle injected as the `live` prop of every generated
 * component. Call `live.pushEvent(name, payload)` to dispatch an event
 * to the mounting LiveView.
 */
export interface LiveHandle {
  pushEvent: (
    event: string,
    payload: object,
    cb?: (reply: unknown) => void
  ) => number;
  pushEventTo: (
    target: string,
    event: string,
    payload: object
  ) => number;
  handleEvent: (event: string, cb: (payload: unknown) => void) => void;
}

export interface Author {
  id: string;
  name: string;
  bio?: string;
  born?: string;
  inserted_at: string;
  updated_at: string;
}

export interface Book {
  id: string;
  title: string;
  isbn?: string;
  published?: boolean;
  price?: string;
  inserted_at: string;
  updated_at: string;
}

export interface Publisher {
  id: string;
  name: string;
  country?: string;
  inserted_at: string;
  updated_at: string;
}

// --- CUSTOM ---
// Custom code below this line is preserved on regeneration.
